engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/**/*
