language: php

php:
  - 7.0

services:
  - mysql

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - bash -c 'wget https://scrutinizer-ci.com/ocular.phar'
    - bash -c 'php ocular.phar code-coverage:upload --format=php-clover coverage.clover'
